name: ios-test

on:
  push:
    paths:
      - "ios/**"
      - ".github/workflows/**"

jobs:
  build-modules:
    name: "iOS Buid Test for Modules"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_12.4.app'
      - name: Show Xcode Version
        run: xcodebuild -version
      - name: Generate Strings & Colors & Assets
        working-directory: ./ios
        run: make run-swiftgen
      - name: Build Test Modules
        working-directory: ./ios
        run: make build-modules

  build-app-debug:
    name: "iOS Buid Test on Debug Configuration"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_12.4.app'
      - name: Show Xcode Version
        run: xcodebuild -version
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: iosTest
          dependencies-cache-key: |
            **/*.gradle
            **/*.gradle.kts
            buildSrc/src/**/*.kt
            **/gradle.properties
            gradle/**
      - name: Generate Strings & Colors & Assets
        working-directory: ./ios
        run: make run-swiftgen
      - name: Build Test for Debug App
        working-directory: ./ios
        run: make build-app-debug

  build-app-release:
    name: "iOS Buid Test on Release Configuration"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_12.4.app'
      - name: Show Xcode Version
        run: xcodebuild -version
      - name: Generate Strings & Colors & Assets
        working-directory: ./ios
        run: make run-swiftgen
      - name: Build Test for Debug App
        working-directory: ./ios
        run: make build-app-release